// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jrlaqueiqjnpzjtsokyd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpybGFxdWVpcWpucHpqdHNva3lkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1ODU5MDcsImV4cCI6MjA2NDE2MTkwN30.ck22r2ZfiEl9vvtuqTiU09MgWzCmcdCWei9TdpSaNyk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);